MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  WEIGHTS: "https://www.dropbox.com/s/1mlv31coewx8trd/vovnet99_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-99-eSE"
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"  
  MASK_ON: True
  MASKIOU_ON: True
  FCOS:
    NUM_CLASSES: 1
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 4000
    POST_NMS_TOPK_TRAIN: 15000
    POST_NMS_TOPK_TEST: 3000
  RPN:
    BATCH_SIZE_PER_IMAGE: 3000
    POST_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 3000
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 3000
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  RETINANET:
    NUM_CLASSES: 1
    TOPK_CANDIDATES_TEST: 3000
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [11.578, 11.578, 11.578]
SOLVER:
  STEPS: (80000, 90000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 2500
DATASETS:
  TRAIN: ("TRAIN",)  #REPLACE TRAIN WITH THE REGISTERED NAME 
  TEST: ("TEST",)    #REPLACE TRAIN WITH THE REGISTERED NAME
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
INPUT:
  MIN_SIZE_TRAIN: (440, 480, 520, 560, 580, 620)
TEST:
  DETECTIONS_PER_IMAGE: 2000 # 1000
DATALOADER:
  NUM_WORKERS: 12
OUTPUT_DIR: ""
